### ISSUE TITLE
Max Combo is being processed wrong

### ISSUE THREAD

**Issue by Dopaminos** [ppy/osu-tools#185]
I wanted to check pp changes on one my map, but max combo is being shown wrong
https://osu.ppy.sh/beatmapsets/2019978 there is 1025 max combo but perfcalc shows 725 or maybe i'm doing something wrong
![image](https://github.com/ppy/osu-tools/assets/42616718/ba081baf-579e-4630-8950-afe584960b48)
![image](https://github.com/ppy/osu-tools/assets/42616718/74f6637a-dc6f-4199-80c1-d9ac96ef1d9e)

**Comment by bdach** [comment]
Select the classic mod and see if that fixes it.

**Comment by Dopaminos** [comment]
yep it does fix. lazer has different combo system?
![image](https://github.com/ppy/osu-tools/assets/42616718/ad13530d-3e70-4769-bc87-d6b6ae2520a9)

**Comment by bdach** [comment]
Sliders themselves don't give combo when classic mod is off, only their constituent parts. This is controlled by the "no slider head accuracy" setting.

This should really be listed on https://github.com/ppy/osu/wiki/Gameplay-differences-from-osu!stable (cc @walavouchey)

**Comment by peppy** [comment]
I'd argue we should probably just bridge the combo gap now that we are adding more choices in judgement results. It doesn't make much sense for the end of a slider to not give combo even though it's a tick.

**Comment by smoogipoo** [comment]
The GUI should probably enable classic mod by default (cc @stanriders . That's what the CLI tool does - and you have to specify `--no-classic` to disable it, and I believe it's a better default while most of this stuff is primarily geared to osu-stable plays.

**Comment by peppy** [comment]
Seems like a valid change until we figure things out from our end 👍 .

**Comment by stanriders** [comment]
> The GUI should probably enable classic mod by default (cc @stanriders). That's what the CLI tool does - you have to specify `--no-classic` to disable it, and I believe it's a better default while most of this stuff is primarily geared to osu-stable plays.

I think I've tried doing that before and UX was a bit questionable, because keeping CL always forsed wasn't something people want and having it enabled by default with an option to turn it off doesn't really help - people who are aware of CL would turn it on themselves anyway and others would turn it off because they don't know what it does.

Other option I see is to add a small text disclaimer above the mod selection button, something like "Don't forget to enable Classic mod if you need full parity with osu!stable scoring"
