### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ThanksMrSotarks** [ppy/osu-tools#21]
when I type
`dotnet PerformanceCalculator.dll`
into Powershell, it returns with 

> No executable found matching command "dotnet-PerformanceCalculator.dll"

where do I go from here?

**Comment by girantinas** [comment]
Where are you opening the powershell window? It must be used in the ~\PerformanceCalculator\bin\Debug\netcoreapp2.0 folder. In any case, make sure you follow VINXIS' video step by step if you're new to this (which we might want to add to the README for newbies).

**Comment by peppy** [comment]
The readme instructions are misleading currently.

Please use

`dotnet run --project PerformanceCalculator`

**Comment by ThanksMrSotarks** [comment]
@girantinas mind linking the said video? idk which one is vinxis' channel

**Comment by peppy** [comment]
The video is not a good guide of how you should be using this project. Please use the local instructions.

**Comment by VINXIS** [comment]
my vid is kind of outdated and was super rushed u should just use the command peppy stated in his comment in the osu-tools main folder

**Comment by VINXIS** [comment]
The issues with both of our videos is that we both told people to download something that is just from us, as well as the fact that both videos were made before more changes were made in the osu repository, ull get it working but it would be suboptimal to follow those methods Instead Of just cloning osu-tools with submodules and updating to the latest, then running `dotnet build` and the command peppy stated to do what u want to do

**Comment by SlowLogicBoy** [comment]
Option 1:
if you want to run .dll you can use:
`osu-tools\PerformanceCalculator\bin\Debug\netcoreapp2.0>dotnet exec PerformanceCalculator.dll`

Option 2:
You can generate .exe by publishing PerformanceCalculator project:
`osu-tools\PerformanceCalculator>dotnet publish -c Release -r win10-x64`
`osu-tools\PerformanceCalculator\bin\Release\netcoreapp2.0\win10-x64>PerformanceCalculator.exe`

**Comment by peppy** [comment]
see #22
